pipeline {
    agent any
    parameters {
        choice(
            name: 'BUILD_IMAGE',
            choices: ['flutter'],
            description: 'Select image for build' ),
        string(
            defaultValue: '2.5.2',
            name: 'Flutter-version'
        )
    }
    stages {
                stage('Build docker') {
                     steps {
                       script {
                            sh "bash docker_build.sh 1.0.${env.BUILD_NUMBER} $BUILD_IMAGE/Dockerfile $params.Flutter-version "
                       }
                    }
                }
    }
}