pipeline {
    agent any

    stages {
                stage('Build docker') {
                environment {
                                        ARTIFACTORY_HOST = "cd1"
                                        }
                     steps {
                       script {
                            sh "bash images/docker_build.sh 1.0.${env.BUILD_NUMBER} "
                       }
                    }
                }
    }
}